"""add end_time to race_sessions

Revision ID: 997265bbfef6
Revises: cd4e3afa5931
Create Date: 2026-07-25 23:38:57.555581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '997265bbfef6'
down_revision: Union[str, Sequence[str], None] = 'cd4e3afa5931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race_sessions', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race_sessions', 'end_time')
    # ### end Alembic commands ###
