"""add website schema fields and tables

Revision ID: cd4e3afa5931
Revises: b00480a73322
Create Date: 2026-07-25 18:59:55.698136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd4e3afa5931'
down_revision: Union[str, Sequence[str], None] = 'b00480a73322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constructor_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('team_color', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constructor_standings_season'), 'constructor_standings', ['season'], unique=False)
    op.create_table('driver_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_standings_season'), 'driver_standings', ['season'], unique=False)
    op.create_table('nfl_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('season_type', sa.String(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('kickoff_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['nfl_teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['nfl_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfl_games_external_id'), 'nfl_games', ['external_id'], unique=False)
    op.create_index(op.f('ix_nfl_games_season'), 'nfl_games', ['season'], unique=False)
    op.create_index(op.f('ix_nfl_games_season_type'), 'nfl_games', ['season_type'], unique=False)
    op.create_index(op.f('ix_nfl_games_week'), 'nfl_games', ['week'], unique=False)
    op.create_table('nfl_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('ties', sa.Integer(), nullable=False),
    sa.Column('division_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['nfl_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfl_standings_season'), 'nfl_standings', ['season'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_external_id'), 'players', ['external_id'], unique=False)
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    op.create_table('race_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_race_sessions_external_id'), 'race_sessions', ['external_id'], unique=False)
    op.create_index(op.f('ix_race_sessions_race_id'), 'race_sessions', ['race_id'], unique=False)
    op.create_index(op.f('ix_race_sessions_session_type'), 'race_sessions', ['session_type'], unique=False)
    op.create_table('standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('draw', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('goal_difference', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standings_competition_id'), 'standings', ['competition_id'], unique=False)
    op.create_index(op.f('ix_standings_group_name'), 'standings', ['group_name'], unique=False)
    op.create_table('injuries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('since', sa.Date(), nullable=True),
    sa.Column('missed_matches', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_injuries_player_id'), 'injuries', ['player_id'], unique=False)
    op.create_index(op.f('ix_injuries_team_id'), 'injuries', ['team_id'], unique=False)
    op.create_table('session_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('laps', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['race_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_results_session_id'), 'session_results', ['session_id'], unique=False)
    op.add_column('competitions', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('competitions', sa.Column('format', sa.String(), nullable=True))
    op.add_column('competitions', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('competitions', sa.Column('external_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_competitions_external_id'), 'competitions', ['external_id'], unique=False)
    op.create_index(op.f('ix_competitions_slug'), 'competitions', ['slug'], unique=False)
    op.add_column('drivers', sa.Column('abbreviation', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('country', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('team_color', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('external_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_drivers_external_id'), 'drivers', ['external_id'], unique=False)
    op.add_column('matches', sa.Column('stage', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('round_name', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('matchday', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('group_name', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('external_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_matches_external_id'), 'matches', ['external_id'], unique=False)
    op.create_index(op.f('ix_matches_stage'), 'matches', ['stage'], unique=False)
    op.add_column('nfl_teams', sa.Column('abbreviation', sa.String(), nullable=True))
    op.add_column('nfl_teams', sa.Column('city', sa.String(), nullable=True))
    op.add_column('nfl_teams', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('nfl_teams', sa.Column('external_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_nfl_teams_abbreviation'), 'nfl_teams', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_nfl_teams_external_id'), 'nfl_teams', ['external_id'], unique=False)
    op.add_column('races', sa.Column('location', sa.String(), nullable=True))
    op.add_column('races', sa.Column('country', sa.String(), nullable=True))
    op.add_column('races', sa.Column('round', sa.Integer(), nullable=True))
    op.add_column('races', sa.Column('external_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_races_external_id'), 'races', ['external_id'], unique=False)
    op.add_column('teams', sa.Column('external_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_teams_external_id'), 'teams', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_external_id'), table_name='teams')
    op.drop_column('teams', 'external_id')
    op.drop_index(op.f('ix_races_external_id'), table_name='races')
    op.drop_column('races', 'external_id')
    op.drop_column('races', 'round')
    op.drop_column('races', 'country')
    op.drop_column('races', 'location')
    op.drop_index(op.f('ix_nfl_teams_external_id'), table_name='nfl_teams')
    op.drop_index(op.f('ix_nfl_teams_abbreviation'), table_name='nfl_teams')
    op.drop_column('nfl_teams', 'external_id')
    op.drop_column('nfl_teams', 'logo_url')
    op.drop_column('nfl_teams', 'city')
    op.drop_column('nfl_teams', 'abbreviation')
    op.drop_index(op.f('ix_matches_stage'), table_name='matches')
    op.drop_index(op.f('ix_matches_external_id'), table_name='matches')
    op.drop_column('matches', 'external_id')
    op.drop_column('matches', 'group_name')
    op.drop_column('matches', 'matchday')
    op.drop_column('matches', 'round_name')
    op.drop_column('matches', 'stage')
    op.drop_index(op.f('ix_drivers_external_id'), table_name='drivers')
    op.drop_column('drivers', 'external_id')
    op.drop_column('drivers', 'team_color')
    op.drop_column('drivers', 'country')
    op.drop_column('drivers', 'abbreviation')
    op.drop_index(op.f('ix_competitions_slug'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_external_id'), table_name='competitions')
    op.drop_column('competitions', 'external_id')
    op.drop_column('competitions', 'logo_url')
    op.drop_column('competitions', 'format')
    op.drop_column('competitions', 'slug')
    op.drop_index(op.f('ix_session_results_session_id'), table_name='session_results')
    op.drop_table('session_results')
    op.drop_index(op.f('ix_injuries_team_id'), table_name='injuries')
    op.drop_index(op.f('ix_injuries_player_id'), table_name='injuries')
    op.drop_table('injuries')
    op.drop_index(op.f('ix_standings_group_name'), table_name='standings')
    op.drop_index(op.f('ix_standings_competition_id'), table_name='standings')
    op.drop_table('standings')
    op.drop_index(op.f('ix_race_sessions_session_type'), table_name='race_sessions')
    op.drop_index(op.f('ix_race_sessions_race_id'), table_name='race_sessions')
    op.drop_index(op.f('ix_race_sessions_external_id'), table_name='race_sessions')
    op.drop_table('race_sessions')
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_index(op.f('ix_players_external_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_nfl_standings_season'), table_name='nfl_standings')
    op.drop_table('nfl_standings')
    op.drop_index(op.f('ix_nfl_games_week'), table_name='nfl_games')
    op.drop_index(op.f('ix_nfl_games_season_type'), table_name='nfl_games')
    op.drop_index(op.f('ix_nfl_games_season'), table_name='nfl_games')
    op.drop_index(op.f('ix_nfl_games_external_id'), table_name='nfl_games')
    op.drop_table('nfl_games')
    op.drop_index(op.f('ix_driver_standings_season'), table_name='driver_standings')
    op.drop_table('driver_standings')
    op.drop_index(op.f('ix_constructor_standings_season'), table_name='constructor_standings')
    op.drop_table('constructor_standings')
    # ### end Alembic commands ###
